services:
  web:
    build: .
    image: aprotech-landing/app:latest
    container_name: aprotech-landing
    restart: always
    env_file:
      - .env.uat
    volumes:
      - .:/code
    ports:
      - '3105:3000'
